### ISSUE TITLE
Add pagination?

### ISSUE THREAD

**Issue by michaelenger** [Giant-Bomb-Preservation-Project/duders-zone#2]
The Quick Looks show has **a lot** of videos and even though the page doesn't break down because of it, it may benefit from some pagination.

**Comment by vegeta897** [comment]
I'd be interested in tackling this.

**Comment by michaelenger** [comment]
@vegeta897 Yes, please do. Feel free to assign this issue to yourself.

Also, to follow the spirit of the page copying the old GB style you should try to ~~steal~~ copy the style of the pagination links from the old site. See the bottom of this page as an example: https://web.archive.org/web/20130326165730/http://www.giantbomb.com/news/
